config/routes.rb
Rails.application.routes.draw do
  resources :contacts do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :title, presence: true, length:{in: 1..140}
    validates :content, presence: true, length:{in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if params[:back]
       render :new
    else
    if @contact.save
       redirect_to contacts_path, notice: "作成しました！"      
    else
      render :new
    end
  end
end

  def edit
  end

  def update
      if @contact.update(contact_params)
        redirect_to contacts_path, notice: "編集しました"
      else
        render :edit
      end
    end

  def show
  end

  def confirm
    @contact = Contact.new(contact_params)
    render :new if @contact.invalid?
  end

  def destroy
    @contact.destroy
    redirect_to contacts_path , notice: "削除しました"
  end
  
  private
  def contact_params
    params.require(:contact).permit(:title , :content)
  end

  def set_contact
    @contact = Contact.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
       confirm_contacts_path
    elsif
       action_name == 'edit'
       contact_path
    end
  end
end

app/views/contacts/_form.html.erb
<%= form_with(model: @contact, local: true, 
              url: choose_new_or_edit) do |form| %>
<% if @contact.errors.any? %>
<div id = "error_explanation">
  <h2><%= @contact.errors.count %>件のエラーがあります。</h2>
  <ul>
  <% @contact.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
  </ul>
  </div>
<% end %>
  <div class="contact_title">
    <%= form.label :タイトル %>
    <%= form.text_field :title %>
  </div>
  <div class="contact_content">
    <%= form.label :内容 %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit :'投稿'%>
<% end %>
<%= link_to "一覧に戻る", contacts_path %>

app/views/contacts/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @contact, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p>タイトル:<%= @contact.title %></p>
  <p>内容:<%= @contact.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit  "戻る" , name: 'back' %>
<% end %>

app/views/contacts/edit.html.erb
<h2>ブログを編集する</h2>
<%= render 'form'%>

app/views/contacts/index.html.erb
<h1>ブログ一覧</h1>
<p><%= notice %></p>
<table>
<tr>
  <th>タイトル</th>
  <th>内容</th>
</tr>
<% @contacts.each do |contact| %>
<tr>
<td><%= contact.title %></td>
<td><%= contact.content %></td>
<td><%= link_to '詳細を確認する', contact_path(contact.id)%></td>
<td><%= link_to "編集する", edit_contact_path(contact.id) %></td>
<td><%= link_to '削除する', contact_path(contact.id), 
        method: :delete, data:{confirm: '本当にok?'} %></td>
</tr>
<% end %>
</table>
<br>
<%= link_to '新しくブログを投稿する', new_contact_path %>

app/views/contacts/new.html.erb
<h2>ブログを作成する</h2>
<%= render 'form'%>

app/views/contacts/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル : <%= @contact.title %></p>
<p>内容 : <%= @contact.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>